### ISSUE TITLE
Combine G1 commands in the queue to reach a full step of max size

### ISSUE THREAD

**Issue by zschwid** [ManufacturedMotion/HexapodControl#23]

**Comment by DillonKane** [comment]
combination of queue length and time since last queue addition.
If step size < step threshold & not idle (timeout), concatenate G1 commands to produce larger step. Otherwise execute (send) the small step

**Comment by DillonKane** [comment]
addressed in https://github.com/ManufacturedMotion/HexapodControl/pull/38
