### ISSUE TITLE
String parsing for stance adjustment

### ISSUE THREAD

**Issue by zschwid** [ManufacturedMotion/HexapodControl#24]
Command format:
G# X# Y#

**Comment by DillonKane** [comment]
@zschwid what number do we want for this / what function does it call? G0 is rapidMove and G1 is linearMoveSetup. If this isn't a new G number and function I'm confused why we need this - G0/G1 will update xyz etc only if they are provided, otherwise they should stay at the previous input

**Comment by DillonKane** [comment]
G9 for stance adjustment, will call hexapod.linearMoveSetup

G1 -> calls Zack's new function; probably hexapod.walkSetup(pos, speed)

**Comment by DillonKane** [comment]
rename fifo to CommandQueue.cpp , etc.

**Comment by DillonKane** [comment]
addressed in https://github.com/ManufacturedMotion/HexapodControl/pull/38
